site_name: Unofficial Symphony Documentation
site_url: http://docs.stratodemo.com
site_description: Symphony documentation testing with MkDocs
site_author: Aries

repo_url: https://github.com/aries-strato/stratodocs/
edit_uri: ""

site_favicon: img/favicon.ico

theme:
  name: readthedocs
  highlightjs: true


copyright: Copyright 2018, 2019 Stratoscale Inc.
google_analytics: [ 'UA-130577010-1', 'docs.stratodemo.com' ]


plugins:
  - search
